stages:
    - test
    - build
    - deploy

run tests:
  stage: test
  image: python:3-alpine3.16
  before_script:
    - apk update
    - apk add --update docker openrc
    - pip install --no-cache-dir -r build/requirements.txt
  script:
    - pytest src/integration/arithmetic_test.py

build:
    stage: build
    image: docker:20.10.16
    services:
        - docker:20.10.16-dind
    variables:
      DOCKER_TLS_CERTDIR: "/certs"
    before_script:
      - docker login -u $DOCKER_USER -p $DOCKER_PWD
    script:
      - cd build
      - docker build -f ./Dockerfile
    after_script:
      - docker push $DOCKER_USER/private_repo:python_app
